---
- name: figure out master IP address
  set_fact: master_ip={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}

- name: add a default route
  command: ip route add default via {{ master_ip }}
  ignore_errors: yes

- name: add a DNS server
  lineinfile:
    destfile: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 8.8.8.8'

- name: add a default root
  lineinfile:
    destfile: /etc/network/interfaces
    insertafter: 'iface eth0 inet static'
    line: '    gateway 192.168.0.1'
